---
colours:
  licorice: &col.licorice "0.000000, 0.000000, 0.000000, 255.000000"
  banana: &col.banana "254.881188, 252.030672, 120.527085, 255.000000"
  snow: &col.snow "255.000000, 255.000000, 255.000000, 255.000000"
  aqua: &col.aqua "0.000000, 150.399228, 255.000000, 255.000000"

states:
  iconButton: &st.iconButton
    on:
      payload:
        BTTTriggerConfig:
          BTTStreamDeckIconColor1: *col.licorice
          BTTStreamDeckBackgroundColor: *col.banana
    off:
      payload:
        BTTTriggerConfig:
          BTTStreamDeckIconColor1: *col.snow
          BTTStreamDeckBackgroundColor: *col.licorice
  textButton: &st.textButton
    on:
      title: "CUE"
      payload:
        BTTTriggerConfig:
          BTTStreamDeckBackgroundColor: *col.aqua
          BTTStreamDeckAttributedTitle:
            "{\\rtf1\\ansi\\ansicpg1252\\cocoartf2820\n\\cocoatextscaling0\\cocoaplatform0{\\fonttbl\\f0\\fnil\\fcharset0
            SFPro-Bold;}\n{\\colortbl;\\red255\\green255\\blue255;\\red0\\green0\\blue0;}\n{\\*\\expandedcolortbl;;\\cssrgb\\c0\\c0\\c0;}\n\\pard\\tx560\\tx1120\\tx1680\\tx2240\\tx2800\\tx3360\\tx3920\\tx4480\\tx5040\\tx5600\\tx6160\\tx6720\\pardirnatural\\qc\\partightenfactor0\n\n\\f0\\b\\fs60
            \\cf2 __TITLE__}"
    off:
      title: "CUE"
      payload:
        BTTTriggerConfig:
          BTTStreamDeckBackgroundColor: *col.licorice
          BTTStreamDeckAttributedTitle:
            "{\\rtf1\\ansi\\ansicpg1252\\cocoartf2820\n\\cocoatextscaling0\\cocoaplatform0{\\fonttbl\\f0\\fnil\\fcharset0
            SFPro-Bold;}\n{\\colortbl;\\red255\\green255\\blue255;\\red255\\green255\\blue255;}\n{\\*\\expandedcolortbl;;\\cspthree\\c100000\\c100000\\c100000;}\n\\pard\\tx560\\tx1120\\tx1680\\tx2240\\tx2800\\tx3360\\tx3920\\tx4480\\tx5040\\tx5600\\tx6160\\tx6720\\pardirnatural\\qc\\partightenfactor0\n\n\\f0\\b\\fs60
            \\cf2 __TITLE__}"

buttons:
  playA:
    uuid: "389804C7-2135-485C-911D-442FCE733BC1"
    states:
      <<: *st.iconButton
  playB:
    uuid: "52894AAF-B332-41A5-85C2-199E950A05D7"
    states:
      <<: *st.iconButton
  cueA:
    uuid: "808CF54F-547E-4230-A836-3A80BE6B2043"
    states:
      <<: *st.textButton
  cueB:
    uuid: "51E2A7A7-6C40-4FD6-A72B-80A75BFABD5E"
    states:
      <<: *st.textButton

midi:
  "2,0,127":
    button: "playA"
    state: "on"
  "2,0,0":
    button: "playA"
    state: "off"
  "3,0,127":
    button: "playB"
    state: "on"
  "3,0,0":
    button: "playB"
    state: "off"
  "2,1,127":
    button: "cueA"
    state: "on"
  "2,1,0":
    button: "cueA"
    state: "off"
  "3,1,127":
    button: "cueB"
    state: "on"
  "3,1,0":
    button: "cueB"
    state: "off"
